name: "Check cherry-picks"

on:
  pull_request:
    paths:
      - .github/workflows/check-cherry-picks.yml
  pull_request_target:
    branches:
      - 'release-**'
      - 'staging-**'
      - '!staging-next'

permissions: {}

jobs:
  check:
    name: cherry-pick-check
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
          filter: blob:none

      - name: Check cherry-picks
        env:
          BASE_SHA: ${{ github.event.pull_request.base.sha }}
          HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        run: |
          ./maintainers/scripts/check-cherry-picks.sh "$BASE_SHA" "$HEAD_SHA"
