name: Codeowners v2
'on':
  pull_request:
    paths:
    - .github/workflows/codeowners-v2.yml
  pull_request_target:
    types:
    - opened
    - ready_for_review
    - synchronize
    - reopened
permissions: {}
env:
  OWNERS_FILE: ci/OWNERS
  DRY_MODE: ${{ github.event.pull_request.draft && '1' || '' }}
jobs:
  get-merge-commit:
    if: github.repository_owner == 'NixOS'
    uses: ./.github/workflows/get-merge-commit.yml
  check:
    name: Check
    runs-on: ubuntu-latest
    needs: get-merge-commit
    if: github.repository_owner == 'NixOS' && needs.get-merge-commit.outputs.mergedSha
    steps:
    - uses: cachix/install-nix-action@526118121621777ccd86f79b04685a9319637641
    - uses: cachix/cachix-action@0fc020193b5a1fa3ac4575aa3a7d3aa6a35435ad
      with:
        name: nixpkgs-ci
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      with:
        path: base
    - name: Build codeowners validator
      run: nix-build base/ci -A codeownersValidator
    - uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e
      if: vars.OWNER_RO_APP_ID
      id: app-token
      with:
        app-id: ${{ vars.OWNER_RO_APP_ID }}
        private-key: ${{ secrets.OWNER_RO_APP_PRIVATE_KEY }}
        permission-administration: read
        permission-members: read
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      with:
        ref: ${{ needs.get-merge-commit.outputs.mergedSha }}
        path: pr
    - name: Validate codeowners
      if: steps.app-token.outputs.token
      run: result/bin/codeowners-validator
      env:
        OWNERS_FILE: pr/${{ env.OWNERS_FILE }}
        GITHUB_ACCESS_TOKEN: ${{ steps.app-token.outputs.token }}
        REPOSITORY_PATH: pr
        OWNER_CHECKER_REPOSITORY: ${{ github.repository }}
        EXPERIMENTAL_CHECKS: avoid-shadowing
  request:
    name: Request
    runs-on: ubuntu-latest
    if: github.repository_owner == 'NixOS'
    steps:
    - uses: cachix/install-nix-action@526118121621777ccd86f79b04685a9319637641
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
    - uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e
      if: vars.OWNER_APP_ID
      id: app-token
      with:
        app-id: ${{ vars.OWNER_APP_ID }}
        private-key: ${{ secrets.OWNER_APP_PRIVATE_KEY }}
        permission-administration: read
        permission-members: read
        permission-pull-requests: write
    - name: Build review request package
      run: nix-build ci -A requestReviews
    - name: Request reviews
      if: steps.app-token.outputs.token
      run: result/bin/request-code-owner-reviews.sh ${{ github.repository }} ${{ github.event.number
        }} "$OWNERS_FILE"
      env:
        GH_TOKEN: ${{ steps.app-token.outputs.token }}
