name: Eval
'on':
  pull_request:
    paths:
    - .github/workflows/eval.yml
  pull_request_target:
    types:
    - opened
    - ready_for_review
    - synchronize
    - reopened
  push:
    branches:
    - master
    - staging
    - release-*
    - staging-*
    - haskell-updates
    - python-updates
permissions: {}
jobs:
  get-merge-commit:
    uses: ./.github/workflows/get-merge-commit.yml
  outpaths:
    name: Outpaths
    runs-on: ubuntu-latest
    needs:
    - get-merge-commit
    strategy:
      fail-fast: false
      matrix:
        system: ${{ fromJSON(needs.get-merge-commit.outputs.systems) }}
    steps:
    - name: Enable swap
      run: 'sudo fallocate -l 10G /swap

        sudo chmod 600 /swap

        sudo mkswap /swap

        sudo swapon /swap

        '
    - name: Check out the PR at the test merge commit
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      with:
        ref: ${{ needs.get-merge-commit.outputs.mergedSha }}
        path: nixpkgs
    - name: Install Nix
      uses: cachix/install-nix-action@526118121621777ccd86f79b04685a9319637641
      with:
        extra_nix_config: sandbox = true
    - name: Evaluate the ${{ matrix.system }} output paths for all derivation attributes
      env:
        MATRIX_SYSTEM: ${{ matrix.system }}
      run: "nix-build nixpkgs/ci -A eval.singleSystem \\\n  --argstr evalSystem \"\
        $MATRIX_SYSTEM\" \\\n  --arg chunkSize 10000\n# If it uses too much memory,\
        \ slightly decrease chunkSize\n"
    - name: Upload the output paths and eval stats
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
      with:
        name: intermediate-${{ matrix.system }}
        path: result/*
  process:
    name: Process
    runs-on: ubuntu-latest
    needs:
    - outpaths
    - get-merge-commit
    outputs:
      targetRunId: ${{ steps.targetRunId.outputs.targetRunId }}
    steps:
    - name: Download output paths and eval stats for all systems
      uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16
      with:
        pattern: intermediate-*
        path: intermediate
    - name: Check out the PR at the test merge commit
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      with:
        ref: ${{ needs.get-merge-commit.outputs.mergedSha }}
        fetch-depth: 2
        path: nixpkgs
    - name: Install Nix
      uses: cachix/install-nix-action@526118121621777ccd86f79b04685a9319637641
      with:
        extra_nix_config: sandbox = true
    - name: Combine all output paths and eval stats
      run: "nix-build nixpkgs/ci -A eval.combine \\\n  --arg resultsDir ./intermediate\
        \ \\\n  -o prResult\n"
    - name: Upload the combined results
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
      with:
        name: result
        path: prResult/*
    - name: Get target run id
      if: needs.get-merge-commit.outputs.targetSha
      id: targetRunId
      run: "# Get the latest eval.yml workflow run for the PR's target commit\nif\
        \ ! run=$(gh api --method GET /repos/\"$REPOSITORY\"/actions/workflows/eval.yml/runs\
        \ \\\n  -f head_sha=\"$TARGET_SHA\" -f event=push \\\n  --jq '.workflow_runs\
        \ | sort_by(.run_started_at) | .[-1]') \\\n  || [[ -z \"$run\" ]]; then\n\
        \  echo \"Could not find an eval.yml workflow run for $TARGET_SHA, cannot\
        \ make comparison\"\n  exit 1\nfi\necho \"Comparing against $(jq .html_url\
        \ <<< \"$run\")\"\nrunId=$(jq .id <<< \"$run\")\nconclusion=$(jq -r .conclusion\
        \ <<< \"$run\")\n\nwhile [[ \"$conclusion\" == null || \"$conclusion\" ==\
        \ \"\" ]]; do\n  echo \"Workflow not done, waiting 10 seconds before checking\
        \ again\"\n  sleep 10\n  conclusion=$(gh api /repos/\"$REPOSITORY\"/actions/runs/\"\
        $runId\" --jq '.conclusion')\ndone\n\nif [[ \"$conclusion\" != \"success\"\
        \ ]]; then\n  echo \"Workflow was not successful (conclusion: $conclusion),\
        \ cannot make comparison\"\n  exit 1\nfi\n\necho \"targetRunId=$runId\" >>\
        \ \"$GITHUB_OUTPUT\"\n"
      env:
        REPOSITORY: ${{ github.repository }}
        TARGET_SHA: ${{ needs.get-merge-commit.outputs.targetSha }}
        GH_TOKEN: ${{ github.token }}
    - uses: actions/download-artifact@v4
      if: steps.targetRunId.outputs.targetRunId
      with:
        name: result
        path: targetResult
        github-token: ${{ github.token }}
        run-id: ${{ steps.targetRunId.outputs.targetRunId }}
    - name: Compare against the target branch
      if: steps.targetRunId.outputs.targetRunId
      run: "git -C nixpkgs worktree add ../target ${{ needs.get-merge-commit.outputs.targetSha\
        \ }}\ngit -C nixpkgs diff --name-only ${{ needs.get-merge-commit.outputs.targetSha\
        \ }} \\\n  | jq --raw-input --slurp 'split(\"\\n\")[:-1]' > touched-files.json\n\
        \n# Use the target branch to get accurate maintainer info\nnix-build target/ci\
        \ -A eval.compare \\\n  --arg beforeResultDir ./targetResult \\\n  --arg afterResultDir\
        \ \"$(realpath prResult)\" \\\n  --arg touchedFilesJson ./touched-files.json\
        \ \\\n  --argstr githubAuthorId \"$AUTHOR_ID\" \\\n  -o comparison\n\ncat\
        \ comparison/step-summary.md >> \"$GITHUB_STEP_SUMMARY\"\n"
      env:
        AUTHOR_ID: ${{ github.event.pull_request.user.id }}
    - name: Upload the combined results
      if: steps.targetRunId.outputs.targetRunId
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
      with:
        name: comparison
        path: comparison/*
  tag:
    name: Tag
    runs-on: ubuntu-latest
    needs:
    - get-merge-commit
    - process
    if: needs.process.outputs.targetRunId
    permissions:
      pull-requests: write
      statuses: write
    steps:
    - uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e
      if: vars.OWNER_APP_ID
      id: app-token
      with:
        app-id: ${{ vars.OWNER_APP_ID }}
        private-key: ${{ secrets.OWNER_APP_PRIVATE_KEY }}
        permission-administration: read
        permission-members: read
        permission-pull-requests: write
    - name: Download process result
      uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16
      with:
        name: comparison
        path: comparison
    - name: Install Nix
      uses: cachix/install-nix-action@526118121621777ccd86f79b04685a9319637641
    - name: Check out Nixpkgs at the base commit
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      with:
        ref: ${{ needs.get-merge-commit.outputs.targetSha }}
        path: base
        sparse-checkout: ci
    - name: Build the requestReviews derivation
      run: nix-build base/ci -A requestReviews
    - name: Labelling pull request
      if: ${{ github.event_name == 'pull_request_target' && github.repository_owner
        == 'NixOS' }}
      run: "# Get all currently set labels that we manage\ngh api \\\n  /repos/\"\
        $REPOSITORY\"/issues/\"$NUMBER\"/labels \\\n  --jq '.[].name | select(startswith(\"\
        10.rebuild\") or . == \"11.by: package-maintainer\")' \\\n  | sort > before\n\
        \n# And the labels that should be there\njq -r '.labels[]' comparison/changed-paths.json\
        \ \\\n  | sort > after\n\n# Remove the ones not needed anymore\nwhile read\
        \ -r toRemove; do\n  echo \"Removing label $toRemove\"\n  gh api \\\n    --method\
        \ DELETE \\\n    /repos/\"$REPOSITORY\"/issues/\"$NUMBER\"/labels/\"$toRemove\"\
        \ndone < <(comm -23 before after)\n\n# And add the ones that aren't set already\n\
        while read -r toAdd; do\n  echo \"Adding label $toAdd\"\n  gh api \\\n   \
        \ --method POST \\\n    /repos/\"$REPOSITORY\"/issues/\"$NUMBER\"/labels \\\
        \n    -f \"labels[]=$toAdd\"\ndone < <(comm -13 before after)\n"
      env:
        GH_TOKEN: ${{ github.token }}
        REPOSITORY: ${{ github.repository }}
        NUMBER: ${{ github.event.number }}
    - name: Add eval summary to commit statuses
      if: ${{ github.event_name == 'pull_request_target' && github.repository_owner
        == 'NixOS' }}
      run: "description=$(jq -r '\n\"Package: added \" + (.attrdiff.added | length\
        \ | tostring) +\n\", removed \" + (.attrdiff.removed | length | tostring)\
        \ +\n\", changed \" + (.attrdiff.changed | length | tostring) +\n\", Rebuild:\
        \ linux \" + (.rebuildCountByKernel.linux | tostring) +\n\", darwin \" + (.rebuildCountByKernel.darwin\
        \ | tostring)\n' <comparison/changed-paths.json)\ntarget_url=\"$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID?pr=$NUMBER\"\
        \ngh api --method POST \\\n  -H \"Accept: application/vnd.github+json\" -H\
        \ \"X-GitHub-Api-Version: 2022-11-28\" \\\n  \"/repos/$GITHUB_REPOSITORY/statuses/$PR_HEAD_SHA\"\
        \ \\\n  -f \"context=Eval / Summary\" -f \"state=success\" -f \"description=$description\"\
        \ -f \"target_url=$target_url\"\n"
      env:
        GH_TOKEN: ${{ github.token }}
        PR_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        NUMBER: ${{ github.event.number }}
    - name: Requesting maintainer reviews
      if: ${{ steps.app-token.outputs.token && github.repository_owner == 'NixOS'
        }}
      run: "# maintainers.json contains GitHub IDs. Look up handles to request reviews\
        \ from.\n# There appears to be no API to request reviews based on GitHub IDs\n\
        jq -r 'keys[]' comparison/maintainers.json \\\n  | while read -r id; do gh\
        \ api /user/\"$id\" --jq .login; done \\\n  | GH_TOKEN=${{ steps.app-token.outputs.token\
        \ }} result/bin/request-reviewers.sh \"$REPOSITORY\" \"$NUMBER\" \"$AUTHOR\"\
        \n"
      env:
        GH_TOKEN: ${{ github.token }}
        REPOSITORY: ${{ github.repository }}
        NUMBER: ${{ github.event.number }}
        AUTHOR: ${{ github.event.pull_request.user.login }}
        DRY_MODE: ${{ github.event.pull_request.draft && '1' || '' }}
